### ISSUE TITLE
support different strategies for writing enum to TypeScript

### ISSUE THREAD

**Issue by atsu85** [raphaeljolivet/java2typescript#13]
It looks like i'm not the only one, who doesn't like to convert java Enums to TypeScript enums.
For example @fgutmann just [exported enums as strings](https://github.com/talk4date/java2typescript/commit/126def5c4c2464f423bb712fc4d9428a6ec22e79#diff-32a70b556c4e723330271ff621f4521eL123), but i don't like that approach either, because i have following goals:
1) JavaScript object containing field of "enum" must contain enum name instead of ordinal value. This is good for several reasons: a) easy to understand JSON content b) doesn't mess things up, if enum order changes in backend.
2) I'd still like to write TypeScript as if i was using real enums - type safety, etc.
3) I should be able to use "reflection" (`instanceof`) to detect if field is "enum"

**Comment by atsu85** [comment]
I'll send a pull request, so that current(default) implementation could be replaced with Typesafe Enum Pattern to fulfill my goals listed above

**Comment by atsu85** [comment]
please merge my [pull request](https://github.com/raphaeljolivet/java2typescript/pull/14) to resolve this issue

**Comment by atsu85** [comment]
When TypeSafe Enum Pattern [is chosen](https://github.com/atsu85/java2typescript/blob/issue-13-customizeWriter/java2typescript-jackson/src/test/java/java2typescript/jackson/module/WriterPreferencesTest.java#L47), then the result looks smth [like this](https://github.com/atsu85/java2typescript/blob/issue-13-customizeWriter/java2typescript-jackson/src/test/java/java2typescript/jackson/module/WriterPreferencesTest.enumToEnumPattern.d.ts)

**Comment by raDiesle** [comment]
+1 - this would be so cool
