### ISSUE TITLE
project doesn't compile after merge request #6

### ISSUE THREAD

**Issue by atsu85** [raphaeljolivet/java2typescript#16]
`mvn clean install` produces following error:
> [ERROR] Failed to execute goal on project java2typescript-jaxrs: Could not resolve dependencies for project java2typescript:java2typescript-jaxrs:jar:0.2-SNAPSHOT: Could not find artifact java2typescript:sample-web-app:jar:0.2-SNAPSHOT -> [Help 1]

**Comment by atsu85** [comment]
That's because @raDiesle created 2 new subprojects that appear to contain everything from sample-web-app, but dependencies are incorrect.

I'll fix the dependencies with pull request soon, but I still have one question:
@raDiesle, should sample-web-app subproject be deleted?

**Comment by atsu85** [comment]
to fix this issue, please merge either pull requests #17 or #18 (that contains code from other merge requests as well, that would otherwise conflict with each other)

**Comment by raDiesle** [comment]
hm, thanks for fixing!
I do neighter remember my pull request nor have an explanation
