### ISSUE TITLE
@raphaeljolivet, allwo travis-ci to access this repository for Continuous Integration

### ISSUE THREAD

**Issue by atsu85** [raphaeljolivet/java2typescript#23]
issue #21 configured this repository to support CI integration through [Travis CI](https://travis-ci.org), 
**so the only thing left to do, is to allow Travis CI to access this repository**.

**@raphaeljolivet, only You (owner of this repository) can do it, but it takes only a minute :)**

Basically, You'll need to
* First go to https://travis-ci.org/ and sign in with your GitHub account.
* In the upper right corner click on your name (or choose Accounts) to open your Travis-ci profile.
You'll be presented with the list of your GitHub projects (only the ones where you have administrative authority)
* Toggle the switch on one of your projects and then click on little wrench icon to open the project's Service Hooks page on GitHub. To get to the same place from your GitHub project, go to Settings > Service Hooks. 

<sup>(these instructions are copied from [here](https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo#integrate-your-github-project-with-travis-ci))</sup>

**Comment by raphaeljolivet** [comment]
Done

**Comment by atsu85** [comment]
Note: now (when first commit was added after travis integration) the build status indicator is also changed from "unknown" to "passing"
