### ISSUE TITLE
release latest from master and publish

### ISSUE THREAD

**Issue by atsu85** [raphaeljolivet/java2typescript#25]
Artifacts should be added to mvn-repo branch, so they could be used for dependency managers, such as maven and gradle (when [that repo](https://github.com/raphaeljolivet/java2typescript/tree/mvn-repo) is included).

**Comment by atsu85** [comment]
If I'm not mistaking `mvn clean deploy` on master branch and project root should do the trick, however it doesn't work for me.

Current pom.xml looks like as it was set up similarly to [this guide](http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github) (with minor differences), however i didn't manage to get it working (even after configuring ~/.m2/settings.xml)

Issues after running `mvn deploy`:
1) `mvn clean deploy`:
```
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.8:site (default) on project java2typescript: Execution default of goal com.github.github:site-maven-plugin:0.8:site failed: basedir C:\tmp\proj\cloned\java2typescript\target\mvn-repo does not exist -> [Help 1]
```
2) creating missing directory and trying again with `mvn clean && mkdir target\mvn-repo && mvn deploy`:
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.8:site (default) on project java2typescript: Execution default of goal com.github.github:site-maven-plugin:0.8:site failed: An API incompatibility was encountered while executing com.github.github:site-maven-plugin:0.8:site: java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;

3) **Here is where I'm stuck**: after updating site-maven-plugin version 0.8 -> 0.12 and running again previous command:
```
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.12:site (default) on project java2typescript: Error creating commit: Invalid request.
[ERROR]
[ERROR] For 'properties/name', nil is not a string.
[ERROR] For 'properties/name', nil is not a string. (422)
[ERROR] -> [Help 1]
...
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating commit: Invalid request.

For 'properties/name', nil is not a string.
For 'properties/name', nil is not a string. (422)
        at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:461)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.eclipse.egit.github.core.client.RequestException: Invalid request.

For 'properties/name', nil is not a string.
For 'properties/name', nil is not a string. (422)
        at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
        at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
        at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
        at org.eclipse.egit.github.core.service.DataService.createCommit(DataService.java:397)
        at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:454)
        ... 21 more
```

**Comment by atsu85** [comment]
@raphaeljolivet, can You comment, how You managed to release version 0.1? Am i missing smth very obvious?

**Comment by atsu85** [comment]
ping @raphaeljolivet - Your comment would be very helpful

**Comment by raphaeljolivet** [comment]
Hi, I dont remember exactly. I know I follow a stackoverflow answer like :
http://stackoverflow.com/a/14013645, and delivered on artifacts on a
separate branch (man-repo). I don't remember encountering any major issue.
You may switch to JitPack, as this answer suggest :
http://stackoverflow.com/a/30035268

Le sam. 2 janv. 2016 à 23:03, atsu85 <notifications@github.com> a écrit :

> @raphaeljolivet <https://github.com/raphaeljolivet>, can You comment, how
> You managed to release version 0.1? Am i missing smth very obvious?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raphaeljolivet/java2typescript/issues/25#issuecomment-168433091>
> .
>
-- 
« Le pire des maux est que le pouvoir soit occupé par ceux qui l’ont voulu
» (Platon)
«Je ne crains pas le suffrage universel : les gens voteront comme on leur
dira » (Alexis de Tocqueville)
http://le-message.org
http://lavraiedemocratie.fr

**Comment by atsu85** [comment]
Thanks @raphaeljolivet, actually as i mentioned [above](https://github.com/raphaeljolivet/java2typescript/issues/25#issuecomment-168431987) i used the same guide, without success. At least some problems were caused by maven version and maven plugin version differences - maybe all of them. I also investigated the JitPack integration at that time, but didn't want to introduce it because You used different mechanism to publish the artifacts.

Anyway, now i also added [the instructions to for resolving dependencies](https://github.com/raphaeljolivet/java2typescript/#installation) though JitPack

**Comment by raphaeljolivet** [comment]
Nice, thanks for all that.
Btw, what kind of project are you using this library for ? Is it also on
github ? Just by curiosity.

Le dim. 10 janv. 2016 à 17:15, atsu85 <notifications@github.com> a écrit :

> Thanks @raphaeljolivet <https://github.com/raphaeljolivet>, actually as i
> mentioned above
> <https://github.com/raphaeljolivet/java2typescript/issues/25#issuecomment-168431987>
> i used the same guide, without success. At least some problems were caused
> by maven version and maven plugin version differences - maybe all of them.
> I also investigated the JitPack integration at that time, but didn't want
> to introduce it because You used different mechanism to publish the
> artifacts.
>
> Anyway, now i also added the instructions to for resolving dependencies
> <https://github.com/raphaeljolivet/java2typescript/#installation> though
> JitPack
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raphaeljolivet/java2typescript/issues/25#issuecomment-170363376>
> .
>
-- 
« Le pire des maux est que le pouvoir soit occupé par ceux qui l’ont voulu
» (Platon)
«Je ne crains pas le suffrage universel : les gens voteront comme on leur
dira » (Alexis de Tocqueville)
http://le-message.org
http://lavraiedemocratie.fr

**Comment by atsu85** [comment]
Hi, i've been using it for [Aurelia](http://aurelia.io/) projects, for 7 months by now, but during Christmas vacation took time to turn my quick hacks into pull requests :) 
[Aurelia is on github](https://github.com/aurelia/), but not my own projects ;)

**Comment by raphaeljolivet** [comment]
-- 
« Le pire des maux est que le pouvoir soit occupé par ceux qui l’ont voulu
» (Platon)
«Je ne crains pas le suffrage universel : les gens voteront comme on leur
dira » (Alexis de Tocqueville)
http://le-message.org
http://lavraiedemocratie.fr
