### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by raDiesle** [raphaeljolivet/java2typescript#5]
Hi, 

would be cool to publish to a repository
or to add a quick documentation how to setup quick.

**Comment by atsu85** [comment]
Hi @raDiesle, I added [the instructions for resolving dependencies](https://github.com/raphaeljolivet/java2typescript/#installation) through JitPack maven repository.

Do You have any ideas/suggestions on how to improve the documentation? Even better - i'd really appreciate pull request.

**Comment by gautamaino** [comment]
I tried to use the plugin using the instructions provided but no luck so far.. 1. setup jitpack repo - used the dependency tag to refer to the V0.3.0-rc1 

		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>

		<dependency>
			<groupId>com.github.raphaeljolivet.java2typescript</groupId>
			<artifactId>java2typescript-maven-plugin</artifactId>
			<version>v0.3.0.rc1</version>
		</dependency>

But its consistently not finding the dependency

**Comment by gautamaino** [comment]
ok. after repeated refreshes I got the dependency in my project so yes it works :) but how do I setup the plugin ? Any examples ?

**Comment by gautamaino** [comment]
Ok. I looked at the plugin configuration in the sample web app. What goal do I need to run to run the java to typescript generators. Irrespective of what I run.. it doesn't seem to do anything. ?

**Comment by atsu85** [comment]
@gautamaino, 
> [There is a single goal generate that generates both .ts and .js files](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-maven-plugin#goals)
`mvn java2typescript:generate`

Note that there was [an issue](https://github.com/raphaeljolivet/java2typescript/issues/45#issuecomment-241889070) related to maven plugin that is now fixed.

**Comment by atsu85** [comment]
> But its consistently not finding the dependency

Maybe You didn't add pluginRepository element (just regular repository)? Anyway I updated the [instructions for maven plugin](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-maven-plugin#setup). I hope it helps
