### ISSUE TITLE
Support for multiple files

### ISSUE THREAD

**Issue by hypery2k** [raphaeljolivet/java2typescript#53]
Is support for multiple files pattern planned?

**Comment by atsu85** [comment]
What do You mean by
> multiple files pattern

?

**Comment by hypery2k** [comment]
I mean providing a regex for the Rest interface class like *my.package.controller.**

**Comment by atsu85** [comment]
Without maven plugin You could implement finding classes (based on regex or java package) Yourself however You want. 

As I'm only using [java2typescript-jackson](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-jackson) without any other modules, I'm not going to implement it myself for [java2typescript-maven-plugin](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-maven-plugin), but I'll accept pull requests for new features.

If You are interested in implementing it for maven plugin, the place You'll need to modify is https://github.com/raphaeljolivet/java2typescript/blob/master/java2typescript-maven-plugin/src/main/java/org/java2typescript/maven/plugin/MainMojo.java#L89-L90 .


---------------


Another approach I'm using myself (without maven or jax-rs, just java2typescript-jackson) is finding specifi subclasses of given type form given package:
```Java
import org.reflections.Reflections;
...
		Reflections r = new Reflections(packageName);
		Set classesForTSD= r.getSubTypesOf(SomeBaseClass.class);
```
and passing them to [DefinitionGenerator.generateTypeScript()](https://github.com/raphaeljolivet/java2typescript/blob/master/java2typescript-jackson/src/main/java/java2typescript/jackson/module/DefinitionGenerator.java#L44) to create TypeScript representation of given classes
```Java
import java2typescript.jackson.module.DefinitionGenerator;
...
		DefinitionGenerator generator = new DefinitionGenerator(new ObjectMapper());
                Configuration conf = null; // You could leave it as null or provide Your own conf
		Module module = generator.generateTypeScript("generated", classesForTSD, conf);
```

and writing the module to OutputStream with ModuleWriter [like this](https://github.com/raphaeljolivet/java2typescript/blob/master/java2typescript-jackson/src/test/java/java2typescript/jackson/module/DefinitionGeneratorTest.java#L91-L92)
