### ISSUE TITLE
Support for only generated TS files only for POJO/DTO objects via maven

### ISSUE THREAD

**Issue by hypery2k** [raphaeljolivet/java2typescript#54]
Is it possible besides to skip the interface generation without using the jackson module directly, so instead include it in this project?

**Comment by atsu85** [comment]
I'm not sure I understood Your goal.

Do You want to 
1) get rid of Jackson dependency (used by [java2typescript-maven-plugin](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-maven-plugin) --> [java2typescript-jaxrs](https://github.com/raphaeljolivet/java2typescript/blob/master/java2typescript-jaxrs) -->[java2typescript-jackson](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-jackson) --> [Jackson](https://github.com/FasterXML/jackson))
or 
2) just avoid generating TypeScript declarations file?

If You don't care about Jackson dependency and just want to generate JavaScript file (like maven plugin does), You could use [ServiceDescriptorGenerator.generateJavascript(String moduleName, Writer writer)](https://github.com/raphaeljolivet/java2typescript/blob/master/java2typescript-jaxrs/src/main/java/java2typescript/jaxrs/ServiceDescriptorGenerator.java#L173) (from [java2typescript-jaxrs](https://github.com/raphaeljolivet/java2typescript/blob/master/java2typescript-jaxrs)) pretty-much the same way as [java2typescript-maven-plugin](https://github.com/raphaeljolivet/java2typescript/blob/master/java2typescript-maven-plugin/src/main/java/org/java2typescript/maven/plugin/MainMojo.java#L89-L105) is doing. From the previously highlighted code leave out [the part that generates TypeScript declarations](https://github.com/raphaeljolivet/java2typescript/blob/master/java2typescript-maven-plugin/src/main/java/org/java2typescript/maven/plugin/MainMojo.java#L92-L98)

Note: I'm not using [java2typescript-maven-plugin](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-maven-plugin) and [java2typescript-jaxrs](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-jaxrs) modules myself (just [java2typescript-jackson](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-jackson)), so I'm not very familiar with that code.

**Comment by atsu85** [comment]
@hypery2k, after reading again the title
> Support for only generated TS files only for POJO/DTO objects via maven

For me it seems to contradict with what You mentioned before:
> skip the interface generation

(I'd assume that by interface generation You mean TypeScript declarations file).
So I'm again very confused as I was initially when starting to read this issue :S

**Comment by hypery2k** [comment]
yes i mean the interface declaration files in TypeScript

**Comment by atsu85** [comment]
@hypery2k, I still don't understand if You want interfaces or not:
> title seems to contradict with what You mentioned before

**Comment by atsu85** [comment]
no response - closing

**Comment by atsu85** [comment]
no response - closing
